repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: ^(stm32/|hardware/)
    -   id: trailing-whitespace
        exclude: ^(stm32/|hardware/)
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format
