//Autogenerated code

#include <stdint.h>
#include <stdbool.h>

typedef struct __attribute__((__packed__)) {
  float x; // x part of the quaternion
  float y; // y part of the quaternion
  float z; // z part of the quaternion
  float w; // w part of the quaternion
} Quaternion;

typedef struct __attribute__((__packed__)) {
  uint8_t attitude_estimation_mode;
  uint16_t current_number_of_matches;
  uint16_t average_number_of_matches;
  Quaternion quaternion; // curent quaternion
  uint16_t estimation_id; // Id of the current attitude estimation sample
} Status;

typedef struct __attribute__((__packed__)) {
  float start; // Start time in seconds
  float stop; // Stop time in seconds
  float coeffs[3][4]; // Polynomial coefficients
} Trajectory;

typedef struct __attribute__((__packed__)) {
  uint8_t min_matches; // Min matches required in the attitude estimation
  uint8_t attitude_estimation_timeout_ms;
  uint16_t exposure_ms;
  uint8_t gain;
} Settings;

typedef struct __attribute__((__packed__)) {
  uint8_t ack; // 1 if acknowledge okay else 0
} Acknowledge;
