name: Build and Push Docker image

on:
  push:
    branches:
      - "**"  # All branches
    tags-ignore:
      - "**"  # Ignore all tags

jobs:

  changes:
    runs-on: ubuntu-22.04
    outputs:
      docker: ${{ steps.filter.outputs.docker }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docker:
              - 'Dockerfile'
              - '.github/workflows/docker.yml'

  build:
    runs-on: ubuntu-22.04
    if: needs.changes.outputs.docker == 'true'

    permissions:
      contents: read
      packages: write   # needed for pushing to GHCR

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: |
            linux/arm64
            linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/startracker-build:latest
            ghcr.io/${{ github.repository_owner }}/startracker-build:${{ github.sha }}
