name: Build and Push Docker image

on:
  push:
    branches: [ "main", "feature/rustification" ]
    paths:
      - "Dockerfile"
      - ".github/workflows/docker.yml" # rebuild only if Dockerfile/workflow changes
  workflow_dispatch: # manual trigger

jobs:
  build:
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      packages: write   # needed for pushing to GHCR

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: |
            linux/arm64
            linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/startracker-build:latest
            ghcr.io/${{ github.repository_owner }}/startracker-build:${{ github.sha }}
