name: Test develop CI/CD Pipeline

on:
  workflow_run:
    workflows: ["Build and Push Docker image"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: ghcr.io/${{ github.repository_owner }}/startracker-build:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # poetry==2.1.4 has a bug
    - name: Install dependencies
      run: |
        pip install poetry==2.1.3
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false

    - name: Pre-commit checks
      run: |
        PYTHONFAULTHANDLER=1 pre-commit run --all-files

    - name: Run pytest
      run: |
        pytest

    - name: Run mypy
      run: |
        mypy

    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
