name: Python CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install .
        pip install -r requirements_dev.txt

    - name: Pre-commit checks
      run: |
        pre-commit run --all-files

    - name: Run pytest
      run: |
        pytest
