name: Test develop CI/CD Pipeline

on:
  push:
    branches:
      - "**"  # All branches
    tags-ignore:
      - "**"  # Ignore all tags


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libclang-dev libcairo2-dev libopencv-dev

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # poetry==2.1.4 has a bug
    - name: Install dependencies
      run: |
        pip install poetry==2.1.3
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false

    - name: Pre-commit checks
      run: |
        PYTHONFAULTHANDLER=1 pre-commit run --all-files

    - name: Run pytest
      run: |
        pytest

    - name: Run mypy
      run: |
        mypy

    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
